### ISSUE TITLE
закрывать editor источник после swapdiff

### ISSUE THREAD

**Issue by av-leschinskiy** [shalimski/swapdiff#1]
Правильно понимаю, что у vscode нет встроенной команды в api чтобы после swapdiffa editor из которого запустили команду сам закрылся?

**Comment by shalimski** [comment]
Идею понял, попробую реализовать.

**Comment by shalimski** [comment]
Добавил настройку, включи её и свап будет происходить в одном окне.

![image](https://user-images.githubusercontent.com/1501405/107873985-696f2f00-6ef1-11eb-95ce-4baaea80430f.png)

**Comment by av-leschinskiy** [comment]
> Добавил настройку, включи её и свап будет происходить в одном окне.
> 
> ![image](https://user-images.githubusercontent.com/1501405/107873985-696f2f00-6ef1-11eb-95ce-4baaea80430f.png)

Работает. Спасибо, это офигенно!
