### ISSUE TITLE
Can't swap temporary unsaved documents

### ISSUE THREAD

**Issue by jokrefta** [shalimski/swapdiff#10]
After #3 was fixed, you can now only swap two documents if they have been saved as files. A new, unsaved document doesn't get recognized as a document to swap. If you open two new untitled documents, put some text in them, and compare them, then you can't swap the diff.

**Comment by shalimski** [comment]
Hi, I can't reproduce this behaviour. Could you please specify vscode version and extension version.

**Comment by jokrefta** [comment]
**VSCode version info**
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Swapdiff version** 0.2.0

To reproduce:
- Create a new text file in VS Code (don't save)
- Create another new text file
- Ctrl+shift+p and choose "File: Compare Active File With...". Compare the two untitled documents you just made
- Try to swap diff documents. Error: "Nothing to swap :("

**Comment by shalimski** [comment]
@jokrefta thanks! i fixed that
