### ISSUE TITLE
Swap for Comparing File with Clipboard

### ISSUE THREAD

**Issue by mglst** [shalimski/swapdiff#23]
I'd like to be able to swap diff views between a file and the clipboard

Steps taken:
1. I have an open file
2. I have some content in my clipboard
3. Run `File: Compare Active File with Clipboard`
4. Run `Swap diff documents`
5. I get `Nothing to swap :(`

The use case I have here is I have chatGPT helping me with writing small scripts, and as I get it to output different versions of the code I want to make sure it isn't making modifications elsewhere where I don't see them. Currently, this works but the new version - which is in my clipboard - is displayed on the left pane and I want it on the right pane

**Comment by shalimski** [comment]
Thanks! Its a bug. I will fixed that
