### ISSUE TITLE
Can't swap when the output pane is also open

### ISSUE THREAD

**Issue by jokrefta** [shalimski/swapdiff#3]
It seems that the Output, Problems, and Debug Console panels at the bottom of the screen are considered "editors" by VS Code. So when you have one of them open, it gets counted in `vscode.window.visibleTextEditors`.  This causes the error message  "More than 2 visible files, can`t swap it :(" and prevents me from swapping a diff while I have one of those panels open.

Edit: If I disable all other extensions besides swapdiff, it works in the Debug Console and the Problems panel but still not in the Output panel.

Seemingly related: 
https://github.com/microsoft/vscode/issues/45188 
https://github.com/Microsoft/vscode/issues/58869
https://stackoverflow.com/questions/60235689/how-to-distinguish-output-panel-from-other-activetexteditor

**Comment by malerba423** [comment]
Just commenting to add another bit in the bucket since I don't see a way to bump / upvote issues
